-- =====================================================================
-- NabKuad — seed data (from Yona_Par_Levels_inventory_TEST.xlsx, Sheet1)
-- 6 locations · 25 categories · 222 products (178 with price from June26)
-- =====================================================================

insert into locations (name, code, sort_order) values
  ('Main Bar','MAIN',1),
  ('Service Bar','SVC',2),
  ('Terrace Bar','TER',3),
  ('Rooftop Bar','ROOF',4),
  ('Store on Pier','PIER',5),
  ('Store on Boat','BOAT',6)
on conflict (name) do nothing;

insert into categories (name, sort_order) values
  ('Vodka',1),
  ('Tequila',2),
  ('Gin',3),
  ('Rum',4),
  ('Whiskey',5),
  ('Brandy & Cognac',6),
  ('Aperitif & Digestif',7),
  ('Liqueurs',8),
  ('White Wine',9),
  ('Red Wine',10),
  ('Rose Wine',11),
  ('Sparkling Wine',12),
  ('Champagne - Large Format',13),
  ('Champagne - Brut',14),
  ('Champagne - Rose',15),
  ('Champagne - Magnum',16),
  ('Beer & Cider',17),
  ('Water',18),
  ('Soft Drink',19),
  ('Bitters',20),
  ('Coffee & Tea',21),
  ('Syrups - Frozen Puree',22),
  ('Syrups',23),
  ('Juices',24),
  ('Cigar & Cigarette',25)
on conflict (name) do nothing;

-- products (sku auto-generated; price_per_unit = null ถ้าไม่มีในไฟล์)
insert into products (category_id, name, sku, capacity_ml, count_mode, price_per_unit) values
  ((select id from categories where name='Vodka'), 'Belvedere 0.70 ml.', 'VDK-001', 700, 'fractional', 1580.00),
  ((select id from categories where name='Vodka'), 'Belvedere Pure Phuket limited Edition 70cl', 'VDK-002', 700, 'fractional', null),
  ((select id from categories where name='Vodka'), 'Belvedere 1,75 ml.', 'VDK-003', 1750, 'fractional', 3030.00),
  ((select id from categories where name='Vodka'), 'Belvedere 10 70 cl', 'VDK-004', 750, 'fractional', null),
  ((select id from categories where name='Vodka'), 'Belvedere 3L', 'VDK-005', 3000, 'fractional', 7295.00),
  ((select id from categories where name='Vodka'), 'Belvedere 6L', 'VDK-006', 6000, 'fractional', 16558.00),
  ((select id from categories where name='Vodka'), 'Grey Goose 750 ml.', 'VDK-007', 750, 'fractional', 1985.00),
  ((select id from categories where name='Vodka'), 'Grey Goose 1.75L', 'VDK-008', 1750, 'fractional', 4400.00),
  ((select id from categories where name='Vodka'), 'Grey Goose Altius 750 ml.', 'VDK-009', 750, 'fractional', 6495.33),
  ((select id from categories where name='Vodka'), 'Grey Goose Altius 1.75L', 'VDK-010', 1750, 'fractional', 14766.36),
  ((select id from categories where name='Vodka'), 'Ciroc 750 ml.', 'VDK-011', 750, 'fractional', 1744.00),
  ((select id from categories where name='Vodka'), 'Ciroc 1.75 cl', 'VDK-012', 1750, 'fractional', null),
  ((select id from categories where name='Vodka'), 'Ciroc 3 L.', 'VDK-013', 3000, 'fractional', 6210.00),
  ((select id from categories where name='Vodka'), 'Ketel one 0.75 ml.', 'VDK-014', 750, 'fractional', 869.00),
  ((select id from categories where name='Vodka'), 'Sminoff 1 L', 'VDK-015', 1000, 'fractional', 785.00),
  ((select id from categories where name='Tequila'), 'Jose Cuervo Especial Reposado 0.7 ml.', 'TEQ-001', 700, 'fractional', 850.00),
  ((select id from categories where name='Tequila'), 'Don Julio Blanco Tequila 75 ml.', 'TEQ-002', 750, 'fractional', 2183.00),
  ((select id from categories where name='Tequila'), 'Don Julio Reposado Tequila 75 ml.', 'TEQ-003', 750, 'fractional', 2898.00),
  ((select id from categories where name='Tequila'), 'Don Julio Anejo Reserva Tequila 75 ml.', 'TEQ-004', 750, 'fractional', null),
  ((select id from categories where name='Tequila'), 'Don Julio 1942 Tequila 75 ml.', 'TEQ-005', 750, 'fractional', 9664.00),
  ((select id from categories where name='Tequila'), 'Don Julio 1942 Tequila 1.75 ml.', 'TEQ-006', 1750, 'fractional', 19329.00),
  ((select id from categories where name='Tequila'), 'Don Julio Ultrima Reserva Tequila 75 ml.', 'TEQ-007', 750, 'fractional', 24162.00),
  ((select id from categories where name='Tequila'), 'Clase Azul Reposado 0.75 ml.', 'TEQ-008', 750, 'fractional', 12190.65),
  ((select id from categories where name='Tequila'), 'Clase Azul Gold Durango 0.75 ml.', 'TEQ-009', 750, 'fractional', 25400.00),
  ((select id from categories where name='Tequila'), 'Clase Azul Anejo 750 ml.', 'TEQ-010', 750, 'fractional', 45700.00),
  ((select id from categories where name='Tequila'), 'Clase Azul Reposado 1.75 ml.', 'TEQ-011', 1750, 'fractional', 33400.00),
  ((select id from categories where name='Tequila'), 'Nakepatron el alto tequila Naked 75 ml', 'TEQ-012', 750, 'fractional', 10790.00),
  ((select id from categories where name='Tequila'), 'Cristalion Tequila Reserva 0.75 ml. 1800', 'TEQ-013', 750, 'fractional', null),
  ((select id from categories where name='Tequila'), 'Patron XO 75cl', 'TEQ-014', 750, 'fractional', null),
  ((select id from categories where name='Gin'), 'Gordon''s Gin 70 cl', 'GIN-001', 750, 'fractional', 757.95),
  ((select id from categories where name='Gin'), 'Tanquaray 0.75 ml.', 'GIN-002', 750, 'fractional', 1061.00),
  ((select id from categories where name='Gin'), 'Tanqueray G.10 0.75 ml.', 'GIN-003', 750, 'fractional', 1875.00),
  ((select id from categories where name='Gin'), 'Bombay Sapphire 0.75 ml.', 'GIN-004', 750, 'fractional', 1119.00),
  ((select id from categories where name='Gin'), 'Hendrick''s 0.7 ml.', 'GIN-005', 700, 'fractional', 2150.00),
  ((select id from categories where name='Gin'), 'Monkey 47 0.5 ml.', 'GIN-006', 500, 'fractional', 1953.00),
  ((select id from categories where name='Gin'), 'The Botanist', 'GIN-007', 700, 'fractional', 2415.39),
  ((select id from categories where name='Gin'), 'Gin Mare', 'GIN-008', 700, 'fractional', null),
  ((select id from categories where name='Gin'), 'Montelobos Tobala', 'GIN-009', 750, 'fractional', null),
  ((select id from categories where name='Rum'), 'Captain Morgan White  0.75 ml.', 'RUM-001', 750, 'fractional', 690.99),
  ((select id from categories where name='Rum'), 'Captain Morgan Dark  0.75 ml.', 'RUM-002', 750, 'fractional', 632.00),
  ((select id from categories where name='Rum'), 'Havana 7y 0.75 ml.', 'RUM-003', 750, 'fractional', 1177.00),
  ((select id from categories where name='Rum'), 'Ron Zacapa 23y 0.75 ml.', 'RUM-004', 750, 'fractional', 2768.00),
  ((select id from categories where name='Rum'), 'Bacardi Gran Reserva Diez 10 Years', 'RUM-005', 700, 'fractional', null),
  ((select id from categories where name='Rum'), 'Chalong Bay Pure Series 0.7 ml.', 'RUM-006', 700, 'fractional', 680.00),
  ((select id from categories where name='Rum'), 'Canario Cachaca', 'RUM-007', 1000, 'fractional', 1060.75),
  ((select id from categories where name='Rum'), 'Ron Zacapa XO', 'RUM-008', 750, 'fractional', null),
  ((select id from categories where name='Rum'), 'Havana Club', 'RUM-009', 750, 'fractional', null),
  ((select id from categories where name='Whiskey'), 'JW Red Label 1L.', 'WHK-001', 1000, 'fractional', 833.00),
  ((select id from categories where name='Whiskey'), 'JW Black Label 0.7 ml.', 'WHK-002', 700, 'fractional', 1301.00),
  ((select id from categories where name='Whiskey'), 'JW Gold Label 0.75 ml.', 'WHK-003', 750, 'fractional', 2027.00),
  ((select id from categories where name='Whiskey'), 'JW Blue Label 0.75 ml.', 'WHK-004', 750, 'fractional', 9166.00),
  ((select id from categories where name='Whiskey'), 'Chivas Regal 12y 0.7 ml.', 'WHK-005', 700, 'fractional', 1273.00),
  ((select id from categories where name='Whiskey'), 'Jack Daniels 0.7 ml.', 'WHK-006', 700, 'fractional', 1168.00),
  ((select id from categories where name='Whiskey'), 'Bulleit Bourbon 0.7 ml.', 'WHK-007', 700, 'fractional', 1259.00),
  ((select id from categories where name='Whiskey'), 'Singleton 12y 0.7 ml.', 'WHK-008', 700, 'fractional', 2097.15),
  ((select id from categories where name='Whiskey'), 'Glenmonangie 18y 0.7 ml.', 'WHK-009', 700, 'fractional', 4640.00),
  ((select id from categories where name='Whiskey'), 'Macallan 15y Double Cask 0.7 ml.', 'WHK-010', 700, 'fractional', 8600.00),
  ((select id from categories where name='Whiskey'), 'Hibiki Blended', 'WHK-011', 700, 'fractional', 5550.00),
  ((select id from categories where name='Whiskey'), 'Macallan 12y Double Cask 0.7 ml.', 'WHK-012', 700, 'fractional', 4770.90),
  ((select id from categories where name='Brandy & Cognac'), 'Hennessy Vsop 0.7 ml.', 'BRC-001', 750, 'fractional', 2658.00),
  ((select id from categories where name='Brandy & Cognac'), 'Hennessy Xo 0.7 ml.', 'BRC-002', 750, 'fractional', 8751.00),
  ((select id from categories where name='Brandy & Cognac'), 'Hennessy Paradis 0.7 ml.', 'BRC-003', 750, 'fractional', 44096.00),
  ((select id from categories where name='Brandy & Cognac'), 'Courvoisier VSOP', 'BRC-004', 750, 'fractional', null),
  ((select id from categories where name='Brandy & Cognac'), 'Hennessy Vs 0.7 ml.', 'BRC-005', 750, 'fractional', 1588.00),
  ((select id from categories where name='Brandy & Cognac'), 'Remy Martin 1738 Accord Royal Cognac 1 L', 'BRC-006', 1000, 'fractional', null),
  ((select id from categories where name='Aperitif & Digestif'), 'Aperol 1L.', 'APD-001', 1000, 'fractional', 1525.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Campari 0.75 ml.', 'APD-002', 750, 'fractional', 1250.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Jagermaister 0.7 ml.', 'APD-003', 700, 'fractional', 1075.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Martini Rosso 1 L.', 'APD-004', 1000, 'fractional', 990.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Martini Extra Dry 1 L.', 'APD-005', 1000, 'fractional', 990.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Martini Bianco 1 L.', 'APD-006', 1000, 'fractional', 990.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Fernet Branca', 'APD-007', 700, 'fractional', 1327.00),
  ((select id from categories where name='Aperitif & Digestif'), 'Ricard 0.7 ml.', 'APD-008', 700, 'fractional', 935.50),
  ((select id from categories where name='Liqueurs'), 'Bailey''s  0.7 ml.', 'LIQ-001', 700, 'fractional', 1083.00),
  ((select id from categories where name='Liqueurs'), 'Chambord 0.7 ml.', 'LIQ-002', 700, 'fractional', 1742.99),
  ((select id from categories where name='Liqueurs'), 'Cherry Hering 0.7 ml.', 'LIQ-003', 700, 'fractional', 1078.40),
  ((select id from categories where name='Liqueurs'), 'Cointreau 0.7 ml.', 'LIQ-004', 700, 'fractional', 1308.41),
  ((select id from categories where name='Liqueurs'), 'D.O.M Benedictine 0.7 ml.', 'LIQ-005', 700, 'fractional', 1679.03),
  ((select id from categories where name='Liqueurs'), 'Drambuie 0.7 ml.', 'LIQ-006', 700, 'fractional', 1568.00),
  ((select id from categories where name='Liqueurs'), 'De Kuyper Blue Curacao 0.7 ml.', 'LIQ-007', 700, 'fractional', 675.00),
  ((select id from categories where name='Liqueurs'), 'De Kuyper Dry Orange 0.7 ml.', 'LIQ-008', 700, 'fractional', 675.00),
  ((select id from categories where name='Liqueurs'), 'De Kuyper Amaretto  0.7 ml.', 'LIQ-009', 700, 'fractional', null),
  ((select id from categories where name='Liqueurs'), 'De Kuyper Triple Sec 0.7 ml.', 'LIQ-010', 700, 'fractional', 675.00),
  ((select id from categories where name='Liqueurs'), 'De Kuyper Peach Liqueur 0.7 ml.', 'LIQ-011', 700, 'fractional', 675.00),
  ((select id from categories where name='Liqueurs'), 'Disaronno Amaretto  0.7 ml.', 'LIQ-012', 700, 'fractional', 950.00),
  ((select id from categories where name='Liqueurs'), 'ST. Germain', 'LIQ-013', 700, 'fractional', 1416.50),
  ((select id from categories where name='Liqueurs'), 'Grand marnier 0.7 ml.', 'LIQ-014', 700, 'fractional', 1771.03),
  ((select id from categories where name='Liqueurs'), 'Kuhlua Coffee Liqueur', 'LIQ-015', 700, 'fractional', 1069.16),
  ((select id from categories where name='Liqueurs'), 'Malibu 0.7 ml.', 'LIQ-016', 700, 'fractional', 777.57),
  ((select id from categories where name='Liqueurs'), 'Midori 0.7 ml.', 'LIQ-017', 700, 'fractional', 1086.20),
  ((select id from categories where name='Liqueurs'), 'Limoncello 0.7 ml.', 'LIQ-018', 700, 'fractional', 780.00),
  ((select id from categories where name='Liqueurs'), 'Molinari Extra Sambuca 1L', 'LIQ-019', 1000, 'fractional', 880.00),
  ((select id from categories where name='Liqueurs'), 'Grappa Nonin Friulano', 'LIQ-020', 700, 'fractional', null),
  ((select id from categories where name='Liqueurs'), 'Tequila Rose 0.70 ml.', 'LIQ-021', 700, 'fractional', 840.00),
  ((select id from categories where name='Liqueurs'), 'GALLIANO Espresso liqueur', 'LIQ-022', 500, 'fractional', null),
  ((select id from categories where name='Liqueurs'), 'Hiram Walker Crème de cacao', 'LIQ-023', 750, 'fractional', null),
  ((select id from categories where name='Liqueurs'), 'Hiram Walker Crème de Cassia', 'LIQ-024', 750, 'fractional', null),
  ((select id from categories where name='Liqueurs'), 'Demonio De Los Andes Pisco 0.70 mi.', 'LIQ-025', 700, 'fractional', null),
  ((select id from categories where name='Liqueurs'), 'Maraschino 1L', 'LIQ-026', 1000, 'fractional', null),
  ((select id from categories where name='White Wine'), 'Kapuka Savvignon Blanc Marlborogh, New Zealand', 'WWN-001', 750, 'fractional', 420.00),
  ((select id from categories where name='White Wine'), 'Prego IGP Delle Venezie Pinot Grigio, Italy', 'WWN-002', 750, 'fractional', 430.00),
  ((select id from categories where name='White Wine'), 'Clear Water, Sauvignon Blanc, Marlborough, New Zealand', 'WWN-003', 750, 'fractional', 545.00),
  ((select id from categories where name='White Wine'), 'Cloudy Bay, Sauvignon Blanc, Marlborogh, New Zealand', 'WWN-004', 750, 'fractional', 1320.00),
  ((select id from categories where name='White Wine'), 'Di Giorgio Frank Sauvignon Blanc', 'WWN-005', 750, 'fractional', 430.00),
  ((select id from categories where name='White Wine'), 'Panfolds Bin 311', 'WWN-006', 750, 'fractional', 1190.00),
  ((select id from categories where name='White Wine'), 'Broglia Gsvi "il Doge" DOCG', 'WWN-007', 750, 'fractional', 750.00),
  ((select id from categories where name='White Wine'), 'Dolce & Gabbana Isoland Etna Bianco DOC', 'WWN-008', 750, 'fractional', null),
  ((select id from categories where name='White Wine'), 'Christophe Patrice Chablis Chardonnay', 'WWN-009', 750, 'fractional', 870.00),
  ((select id from categories where name='White Wine'), 'Domain Chaveau, Pouilly Fume,La Charmette Sauvignon Blanc, France', 'WWN-010', 750, 'fractional', 980.00),
  ((select id from categories where name='White Wine'), 'Michel Thomas & Fils Sancerre, France', 'WWN-011', 750, 'fractional', 2805.00),
  ((select id from categories where name='White Wine'), 'Michel Thomas & Fils Sancerre, France', 'WWN-012', 1500, 'fractional', 2805.00),
  ((select id from categories where name='White Wine'), 'Alto Los Romeros Sauvignon Blanc, 75cl, 2023, Chile  boozia', 'WWN-013', 750, 'fractional', null),
  ((select id from categories where name='White Wine'), 'GOLDEN PAWS Chardonnay boozia', 'WWN-014', 750, 'fractional', null),
  ((select id from categories where name='White Wine'), 'TARIQUET PREMIERE GRIVE   iws', 'WWN-015', 750, 'fractional', null),
  ((select id from categories where name='Red Wine'), 'De Bortoli Family Selection, Shiraz, Australia', 'RWN-001', 750, 'fractional', 360.00),
  ((select id from categories where name='Red Wine'), 'Villa Marin Pinot Noir Marlborough, New Zealand', 'RWN-002', 750, 'fractional', 595.00),
  ((select id from categories where name='Red Wine'), 'Alamos Malbec', 'RWN-003', 750, 'fractional', 550.00),
  ((select id from categories where name='Red Wine'), 'Patriarche Endless Summer Pinot Noir Pays D''OC,France', 'RWN-004', 750, 'fractional', 515.00),
  ((select id from categories where name='Red Wine'), 'Chianti Riserva Rocca Delle Macie DOCG, Italy', 'RWN-005', 750, 'fractional', 620.00),
  ((select id from categories where name='Red Wine'), 'Amarone Della Valpolicella Classic, Le Preare DOCG, Italy', 'RWN-006', 750, 'fractional', 930.00),
  ((select id from categories where name='Red Wine'), 'Chateau de Barry, Saint-Emillion Grand Cru, Bordeaux, AOC', 'RWN-007', 750, 'fractional', 930.00),
  ((select id from categories where name='Red Wine'), 'Chateau Du Pape, La Fiole Du Pape', 'RWN-008', 750, 'fractional', 2325.00),
  ((select id from categories where name='Red Wine'), 'Chateau Du Pape, La Fiole Du Pape', 'RWN-009', 1500, 'fractional', 2325.00),
  ((select id from categories where name='Red Wine'), 'Trivento Reserve Cabernet Sauvignon iws', 'RWN-010', 750, 'fractional', null),
  ((select id from categories where name='Red Wine'), '1864  Cabernet Sauvignon, Merlot boozia', 'RWN-011', 750, 'fractional', null),
  ((select id from categories where name='Red Wine'), 'MAISON BARBOULET  Pinot Noir  iws', 'RWN-012', 750, 'fractional', null),
  ((select id from categories where name='Rose Wine'), 'L''Ostal Cazes IGP Pays d''Oc Rose, France', 'RSW-001', 750, 'fractional', 460.00),
  ((select id from categories where name='Rose Wine'), 'M de Minuity, Côtes de Provence, France', 'RSW-002', 750, 'fractional', 790.00),
  ((select id from categories where name='Rose Wine'), 'Chateau Minuity, Rose Et Or, France', 'RSW-003', 750, 'fractional', 1350.00),
  ((select id from categories where name='Rose Wine'), 'Chateau Minuity 281', 'RSW-004', 750, 'fractional', 2900.00),
  ((select id from categories where name='Rose Wine'), 'Whispering Angel 0.75 L', 'RSW-005', 750, 'fractional', 782.00),
  ((select id from categories where name='Rose Wine'), 'Whispering Angel 1.5 L', 'RSW-006', 1500, 'fractional', 3750.00),
  ((select id from categories where name='Rose Wine'), 'Whispering Angel 3 L', 'RSW-007', 3000, 'fractional', 7812.00),
  ((select id from categories where name='Rose Wine'), 'Whispering Angel 6 L', 'RSW-008', 6000, 'fractional', 13600.00),
  ((select id from categories where name='Rose Wine'), 'Domain OTT, Côtes de Provence, France 0.75 L', 'RSW-009', 750, 'fractional', 1040.00),
  ((select id from categories where name='Rose Wine'), 'Domain OTT, Côtes de Provence, France 1.5 L', 'RSW-010', 1500, 'fractional', 2400.00),
  ((select id from categories where name='Rose Wine'), 'Domain OTT, Côtes de Provence, France 3 L', 'RSW-011', 3000, 'fractional', 8000.00),
  ((select id from categories where name='Rose Wine'), 'Talamonti Cerasuolo d''Abruzzo rose', 'RSW-012', 750, 'fractional', null),
  ((select id from categories where name='Rose Wine'), 'BORN ROSE 0.75L', 'RSW-013', 750, 'fractional', null),
  ((select id from categories where name='Rose Wine'), 'BORN ROSE 1.75L', 'RSW-014', 1750, 'fractional', null),
  ((select id from categories where name='Rose Wine'), 'BORN ROSE 3 L', 'RSW-015', 3000, 'fractional', null),
  ((select id from categories where name='Rose Wine'), 'Alpaca rose', 'RSW-016', 750, 'fractional', 524.30),
  ((select id from categories where name='Sparkling Wine'), 'Chandon Brut Australia 75 cl', 'SPK-001', 750, 'fractional', 640.00),
  ((select id from categories where name='Sparkling Wine'), 'Chandon Rosé Australia 75 cl', 'SPK-002', 750, 'fractional', null),
  ((select id from categories where name='Sparkling Wine'), 'Louis Perdrier Brut Excellence 75cl', 'SPK-003', 750, 'fractional', 420.00),
  ((select id from categories where name='Champagne - Large Format'), 'Nicolas Feuillatte Brut 12 L.', 'CHL-001', 750, 'fractional', 63160.00),
  ((select id from categories where name='Champagne - Large Format'), 'Nicolas Feuillatte Brut 1.5L', 'CHL-002', 750, 'fractional', 63160.00),
  ((select id from categories where name='Champagne - Large Format'), 'Nicolas Feuillatte Brut 750ml', 'CHL-003', 750, 'fractional', 63160.00),
  ((select id from categories where name='Champagne - Large Format'), 'Moet Chandon Brut 6 L.', 'CHL-004', 750, 'fractional', 27024.00),
  ((select id from categories where name='Champagne - Large Format'), 'Moet Chandon Brut 3 L.', 'CHL-005', 750, 'fractional', 13518.00),
  ((select id from categories where name='Champagne - Large Format'), 'Dom Perignon Luminous 3 L.', 'CHL-006', 750, 'fractional', null),
  ((select id from categories where name='Champagne - Large Format'), 'Louis Cristal Brut 3 L.', 'CHL-007', 750, 'fractional', 60000.00),
  ((select id from categories where name='Champagne - Brut'), 'Moet Chandon Brut 0.75 L.', 'CHB-001', 750, 'fractional', 1877.00),
  ((select id from categories where name='Champagne - Brut'), 'Vueve cliquot Brut 0.75 L.', 'CHB-002', 750, 'fractional', 1945.00),
  ((select id from categories where name='Champagne - Brut'), 'Moet Chandon Ice 0.75 L.', 'CHB-003', 750, 'fractional', 2353.00),
  ((select id from categories where name='Champagne - Brut'), 'Ruinart Blanc De Blanc', 'CHB-004', 750, 'fractional', 2790.00),
  ((select id from categories where name='Champagne - Brut'), 'Ruinart Blanc De Blanc rose', 'CHB-005', 750, 'fractional', 2790.00),
  ((select id from categories where name='Champagne - Brut'), 'Perrier-Jouet Grand Brut', 'CHB-006', 750, 'fractional', 4524.00),
  ((select id from categories where name='Champagne - Brut'), 'Perrier-Jouet Belle Epoque', 'CHB-007', 750, 'fractional', 11794.00),
  ((select id from categories where name='Champagne - Brut'), 'Louis Cristal Brut 0.75 L.', 'CHB-008', 750, 'fractional', 10000.00),
  ((select id from categories where name='Champagne - Brut'), 'DOM Perignon Brut 0.75 L.', 'CHB-009', 750, 'fractional', 7605.00),
  ((select id from categories where name='Champagne - Brut'), 'DOM Perignon P2  Brut 0.75 L.', 'CHB-010', 750, 'fractional', 16295.00),
  ((select id from categories where name='Champagne - Brut'), 'Arman De Brignac 0.75 L.', 'CHB-011', 750, 'fractional', 10360.00),
  ((select id from categories where name='Champagne - Rose'), 'Moet Chandon Rose 0.75 L.', 'CHR-001', 750, 'fractional', 2426.00),
  ((select id from categories where name='Champagne - Rose'), 'Vueve cliquot Rose 0.75 L.', 'CHR-002', 750, 'fractional', 2533.00),
  ((select id from categories where name='Champagne - Rose'), 'DOM Perignon Rose 0.75 L.', 'CHR-003', 750, 'fractional', 14880.00),
  ((select id from categories where name='Champagne - Rose'), 'Louis Cristal Rose 0.75l', 'CHR-004', 750, 'fractional', 11000.00),
  ((select id from categories where name='Champagne - Magnum'), 'Moet Chandon Brut 1.5 L.', 'CHM-001', 1500, 'fractional', 4129.00),
  ((select id from categories where name='Champagne - Magnum'), 'Louis Cristal Brut 1.5 L.', 'CHM-002', 1500, 'fractional', 25000.00),
  ((select id from categories where name='Champagne - Magnum'), 'Vueve cliquot Brut 1.5 L.', 'CHM-003', 1500, 'fractional', 4305.00),
  ((select id from categories where name='Champagne - Magnum'), 'DOM Perignon Brut 1.5L', 'CHM-004', 1500, 'fractional', 22650.00),
  ((select id from categories where name='Beer & Cider'), 'Singha  320ml', 'BER-001', 320, 'unit', null),
  ((select id from categories where name='Beer & Cider'), 'Corona Beer 330ml.', 'BER-002', 320, 'unit', null),
  ((select id from categories where name='Beer & Cider'), 'Singha Reserve  (I=24)', 'BER-003', 320, 'unit', null),
  ((select id from categories where name='Water'), 'Evian Still mineral 750 ml', 'WTR-001', 750, 'unit', 54.40),
  ((select id from categories where name='Water'), 'Evian Sparkling 0.75 L', 'WTR-002', 750, 'unit', 70.00),
  ((select id from categories where name='Soft Drink'), 'SD-Coke Cola  (I=24)', 'SFT-001', 330, 'unit', 13.56),
  ((select id from categories where name='Soft Drink'), 'SD-Coke Zero  (I=24)', 'SFT-002', 330, 'unit', 13.56),
  ((select id from categories where name='Soft Drink'), 'SD-Sprite  (I=24)', 'SFT-003', 330, 'unit', 13.56),
  ((select id from categories where name='Soft Drink'), 'SD-Schweppes Ginger Ale  (I=24)', 'SFT-004', 330, 'unit', 13.17),
  ((select id from categories where name='Soft Drink'), 'SD-Schweppes Tonic  (I=24)', 'SFT-005', 330, 'unit', 13.19),
  ((select id from categories where name='Soft Drink'), 'SD-Schweppes Manao Soda  (I=24)', 'SFT-006', 330, 'unit', 13.19),
  ((select id from categories where name='Soft Drink'), 'Fever Tree tonic (1=12)', 'SFT-007', 220, 'unit', 55.03),
  ((select id from categories where name='Soft Drink'), 'Fever Tree Ginger Beer (1=12)', 'SFT-008', 220, 'unit', 55.03),
  ((select id from categories where name='Soft Drink'), 'SD-Red Bull   (I=24)', 'SFT-009', 330, 'unit', 63.00),
  ((select id from categories where name='Soft Drink'), 'SD-Schweppes Soda  (I=24)', 'SFT-010', 330, 'unit', 13.19),
  ((select id from categories where name='Bitters'), 'Angostura Aromatic Bitters', 'BIT-001', 250, 'fractional', null),
  ((select id from categories where name='Bitters'), 'Cocktail Enhancer 120 ML.', 'BIT-002', 150, 'fractional', null),
  ((select id from categories where name='Coffee & Tea'), 'Lavazza Napoli Whole Beans Intensity', 'CFT-001', 500, 'unit', null),
  ((select id from categories where name='Coffee & Tea'), 'English Breakfast', 'CFT-002', 1, 'unit', 154.00),
  ((select id from categories where name='Coffee & Tea'), 'Peppermint Leaves', 'CFT-003', 1, 'unit', 154.00),
  ((select id from categories where name='Coffee & Tea'), 'Camomile Flowers', 'CFT-004', 1, 'unit', 154.00),
  ((select id from categories where name='Coffee & Tea'), 'Jasmine', 'CFT-005', 1, 'unit', 154.00),
  ((select id from categories where name='Coffee & Tea'), 'Earl Grey', 'CFT-006', 1, 'unit', 154.00),
  ((select id from categories where name='Coffee & Tea'), 'Lemon Tea', 'CFT-007', 1, 'unit', 98.00),
  ((select id from categories where name='Syrups - Frozen Puree'), 'H/M  STRAWBERRY PUREE', 'SYP-001', 1, 'unit', null),
  ((select id from categories where name='Syrups - Frozen Puree'), 'H/M MANGO PUREE', 'SYP-002', 1, 'unit', null),
  ((select id from categories where name='Syrups - Frozen Puree'), 'H/M PASSION PUREE', 'SYP-003', 1, 'unit', null),
  ((select id from categories where name='Syrups - Frozen Puree'), 'FZ.Passion fruit puree seedless', 'SYP-004', 1, 'unit', 150.00),
  ((select id from categories where name='Syrups'), 'MONIN PEACH PUREE', 'SYR-001', 1000, 'fractional', 550.00),
  ((select id from categories where name='Syrups'), 'MONIN YUZU PUREE', 'SYR-002', 1000, 'fractional', 600.00),
  ((select id from categories where name='Syrups'), 'MONIN ALMOND OGREAT SYRUP', 'SYR-003', 700, 'fractional', 365.00),
  ((select id from categories where name='Syrups'), 'MONIN VANILLA SYRUP', 'SYR-004', 700, 'fractional', 365.00),
  ((select id from categories where name='Syrups'), 'MONIN CAREMEL SYRUP', 'SYR-005', 700, 'fractional', 365.00),
  ((select id from categories where name='Syrups'), 'MONIN GRENADINE SYRUP', 'SYR-006', 700, 'fractional', 250.00),
  ((select id from categories where name='Syrups'), 'MONIN EDDIE FLOWER SYRUP', 'SYR-007', 700, 'fractional', 297.00),
  ((select id from categories where name='Syrups'), 'MONIN LYCHEE SYRUP', 'SYR-008', 700, 'fractional', 388.00),
  ((select id from categories where name='Syrups'), 'MONIN RASPBERRY PUREE', 'SYR-009', 1000, 'fractional', 550.00),
  ((select id from categories where name='Syrups'), 'MONIN Yelllow Banana 700ml', 'SYR-010', 700, 'fractional', 365.00),
  ((select id from categories where name='Syrups'), 'MONIN Kiwi Puree Fruit Mix 1 L.', 'SYR-011', 1000, 'fractional', null),
  ((select id from categories where name='Syrups'), 'MONIN Chocolate Cookie 700 ml', 'SYR-012', 700, 'fractional', null),
  ((select id from categories where name='Juices'), 'JUICE-Apple Juice Malee 1 L.', 'JUC-001', 1000, 'unit', 70.09),
  ((select id from categories where name='Juices'), 'JUICE-Cranberry Juice Tipco 1 L.', 'JUC-002', 1000, 'unit', 59.81),
  ((select id from categories where name='Juices'), 'JUICE-Orange Juice Malee 1L', 'JUC-003', 1000, 'unit', 73.83),
  ((select id from categories where name='Juices'), 'JUICE-Pinapple Juice Malee 1L', 'JUC-004', 1000, 'unit', 73.83),
  ((select id from categories where name='Juices'), 'JUICE-Tomato Juice 1L', 'JUC-005', 1000, 'unit', 65.41),
  ((select id from categories where name='Cigar & Cigarette'), 'MAROBORO LIGHT (Cutton =10)', 'CIG-001', 1, 'unit', 140.18),
  ((select id from categories where name='Cigar & Cigarette'), 'Romeo and Julietta No 3 small', 'CIG-002', 1, 'unit', 790.00),
  ((select id from categories where name='Cigar & Cigarette'), 'Romeo and Julietta No 1  Big', 'CIG-003', 1, 'unit', 790.00),
  ((select id from categories where name='Cigar & Cigarette'), 'Montecristo No 2  Big', 'CIG-004', 1, 'unit', 2023.00),
  ((select id from categories where name='Cigar & Cigarette'), 'Montecristo No 4 small', 'CIG-005', 1, 'unit', 2023.00),
  ((select id from categories where name='Cigar & Cigarette'), 'Partagas Serie D No.4', 'CIG-006', 1, 'unit', 1870.00)
on conflict (sku) do nothing;
